from datetime import datetime
from typing import List, Optional
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import relationship, declarative_base

Base = declarative_base()

# Many-to-many relationship helper table for Alerts and Logs associated with an alert
# In a real SIEM, an alert might point to one or more specific logs that triggered it.
alert_log_association = Table = None # We can use a direct ForeignKey on Alert to the triggering log or a link table.
# Let's keep it simple and clean: an Alert has a foreign key to the primary triggering log, and can optionally link to others.

class DetectionRule(Base):
    """
    Represents threat detection rules used by the correlation engine.
    """
    __tablename__ = "detection_rules"

    id = Column(String(50), primary_key=True, index=True) # e.g. "RULE-AUTH-BRUTEFORCE"
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)
    pattern = Column(String(255), nullable=False) # regex pattern or search keyword
    severity = Column(String(20), nullable=False) # LOW, MEDIUM, HIGH, CRITICAL
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    # Relationships
    alerts = relationship("Alert", back_populates="rule")


class SecurityLog(Base):
    """
    Structured model representing parsed security log events.
    """
    __tablename__ = "security_logs"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.now, index=True)
    event_type = Column(String(50), nullable=False, index=True) # e.g., "auth", "firewall", "web"
    severity = Column(String(20), nullable=False, index=True) # INFO, WARNING, ERROR, CRITICAL
    source_ip = Column(String(45), nullable=True, index=True)
    destination_ip = Column(String(45), nullable=True)
    source_port = Column(Integer, nullable=True)
    destination_port = Column(Integer, nullable=True)
    message = Column(Text, nullable=False)
    raw_payload = Column(Text, nullable=False)
    geo_country = Column(String(100), nullable=True)
    user_agent = Column(String(255), nullable=True)
    user_id = Column(String(100), nullable=True)

    # Relationships
    alerts = relationship("Alert", back_populates="trigger_log")


class IncidentCase(Base):
    """
    A case ticket representing an ongoing security incident under investigation.
    """
    __tablename__ = "incident_cases"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    title = Column(String(150), nullable=False)
    status = Column(String(30), default="OPEN", index=True) # OPEN, IN_PROGRESS, CLOSED
    severity = Column(String(20), nullable=False, index=True) # LOW, MEDIUM, HIGH, CRITICAL
    assigned_to = Column(String(100), nullable=True, default="Unassigned")
    created_at = Column(DateTime, default=datetime.now, index=True)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)

    # Relationships
    alerts = relationship("Alert", back_populates="case")


class Alert(Base):
    """
    Security alert generated by the detection engine when correlation rules trigger.
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.now, index=True)
    rule_id = Column(String(50), ForeignKey("detection_rules.id"), nullable=False)
    trigger_log_id = Column(Integer, ForeignKey("security_logs.id"), nullable=False)
    title = Column(String(150), nullable=False)
    description = Column(Text, nullable=False)
    severity = Column(String(20), nullable=False, index=True) # LOW, MEDIUM, HIGH, CRITICAL
    status = Column(String(20), default="NEW", index=True) # NEW, ACKNOWLEDGED, RESOLVED
    ai_summary = Column(Text, nullable=True) # AI explained context
    ai_playbook = Column(Text, nullable=True) # AI remediation playbook (JSON string or text)
    case_id = Column(Integer, ForeignKey("incident_cases.id"), nullable=True)

    # Relationships
    rule = relationship("DetectionRule", back_populates="alerts")
    trigger_log = relationship("SecurityLog", back_populates="alerts")
    case = relationship("IncidentCase", back_populates="alerts")
